# Generated by Django 5.2.5 on 2025-08-15 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarttools', '0002_remove_flashcard_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flashcard',
        ),
    ]
