# Generated by Django 5.2.5 on 2025-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('cm', 'Computer Engineering'), ('me', 'Mechanical Engineering'), ('ee', 'Electrical Engineering'), ('cv', 'Civil Engineering')], max_length=50, null=True),
        ),
    ]
