# Generated by Django 5.2.4 on 2025-08-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(verbose_name=['category'])),
                ('message', models.TextField(verbose_name=['message'])),
            ],
        ),
    ]
