# Generated by Django 5.2.4 on 2025-08-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='category',
            field=models.CharField(verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
    ]
