# Generated by Django 5.2.4 on 2025-08-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_doubt_category_alter_doubt_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doubt',
        ),
    ]
