# Generated by Django 5.2.4 on 2025-08-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='category',
            field=models.CharField(choices=[('technical', '💻 Technical Question'), ('academic', '📘 Academic Doubt'), ('career', '🎯 Career Guidance'), ('general', 'ℹ️ General Query')], max_length=20),
        ),
    ]
