# Generated by Django 5.2.4 on 2025-08-15 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('notes', 'Study Notes'), ('assignment', 'Assignment'), ('question', 'Question Paper')], max_length=20)),
                ('branch', models.CharField(choices=[('CO', 'Computer Engineering'), ('CE', 'Civil Engineering'), ('E&TC', 'Electrical & Telecommunication Engineering'), ('Mech', 'Mechanical Engineering')], max_length=20)),
                ('semester', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='faculty_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
