# Generated by Django 5.2.4 on 2025-08-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyzone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcontent',
            name='semester',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='uploadedcontent',
            name='subject',
            field=models.CharField(max_length=120),
        ),
    ]
