# Generated by Django 5.2.4 on 2025-08-15 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyzone', '0004_remove_studynote_uploaded_by_facultynote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultynote',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultyzone_facultynotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
