# Generated by Django 5.2.4 on 2025-08-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyzone', '0005_alter_facultynote_uploaded_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyNote',
        ),
    ]
