# Generated by Django 5.2.4 on 2025-08-16 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AptitudeQuestion',
        ),
        migrations.DeleteModel(
            name='CareerQuizQuestion',
        ),
        migrations.DeleteModel(
            name='HRQuestion',
        ),
        migrations.DeleteModel(
            name='InterviewVideo',
        ),
        migrations.DeleteModel(
            name='ProjectIdea',
        ),
        migrations.DeleteModel(
            name='ResumeTemplate',
        ),
    ]
