# Generated by Django 5.2.5 on 2025-08-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectidea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='career/project_images/'),
        ),
        migrations.AlterField(
            model_name='projectidea',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated tech stack', max_length=150),
        ),
    ]
