# Generated by Django 5.2.5 on 2025-08-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_projectidea_image_alter_projectidea_tech_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectidea',
            name='image',
        ),
        migrations.AlterField(
            model_name='projectidea',
            name='tech_stack',
            field=models.CharField(max_length=150),
        ),
    ]
