# Generated by Django 5.2.5 on 2025-08-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_remove_projectidea_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectidea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='career/project_images/'),
        ),
    ]
