# Generated by Django 5.2.5 on 2025-08-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousYearPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('branch', models.CharField(choices=[('CE', 'Computer Engineering'), ('MECH', 'Mechanical Engineering'), ('ETC', 'Electronics & Telecommunication'), ('CIVIL', 'Civil')], max_length=20)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('subject', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('exam_type', models.CharField(choices=[('Winter', 'Winter'), ('Summer', 'Summer')], max_length=10)),
                ('file', models.FileField(upload_to='question_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PreviousPaper',
        ),
    ]
