# Generated by Django 5.2.5 on 2025-08-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_previousyearpaper_delete_previouspaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultynote',
            name='branch',
            field=models.CharField(choices=[('CO', 'Computer Engineering'), ('Mech', 'Mechanical Engineering'), ('E&TC', 'Electrical & Telecommunication Engineering'), ('CE', 'Civil Engineering')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facultynote',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')]),
        ),
        migrations.AlterField(
            model_name='previousyearpaper',
            name='branch',
            field=models.CharField(choices=[('CO', 'Computer Engineering'), ('Mech', 'Mechanical Engineering'), ('E&TC', 'Electrical & Telecommunication Engineering'), ('CE', 'Civil Engineering')], max_length=20),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='branch',
            field=models.CharField(choices=[('CO', 'Computer Engineering'), ('Mech', 'Mechanical Engineering'), ('E&TC', 'Electrical & Telecommunication Engineering'), ('CE', 'Civil Engineering')], max_length=20),
        ),
    ]
