# Generated by Django 5.2.4 on 2025-08-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_facultynote_branch_alter_facultynote_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousyearpaper',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')]),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')]),
        ),
    ]
