# Generated by Django 5.2.5 on 2025-08-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_facultynote_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultynote',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
