# Generated by Django 5.2.4 on 2025-08-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('exam', 'Exam'), ('result', 'Result'), ('deadline', 'Deadline'), ('general', 'General')], default='general', max_length=20)),
                ('link', models.URLField(blank=True, help_text='Optional URL for more details', null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notifications_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(help_text='Date after which notification is no longer shown')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
